# Server configurations
server:
  host: "localhost"
  port: 8080
  secret: "1EB8F5E4C45CBEB96715894759FB2"

# Database credentials
database:
  host: "localhost"
  dbName: "indoquran"
  user: "indoquran"
  pass: "indoquran"

# Logging setup
logger:
  path: "./"
  filename: "logger.log"
