# Server configurations
server:
  host: "localhost"
  port: 8080
  secret: "1EB8F5E4C45CBEB96715894759FB2"

redis:
  host: "localhost"
  port: "6379"

# Database credentials
database:
  host: "localhost:27017"
  dbName: "indoquran"
  username: "indoquran"
  password: "indoquran"

session:
  expire: 1440 #minutes
