version: "3.3"

services:
  mongodb:
    image: "bitnami/mongodb:latest"
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb_data:/bitnami"
  mariadb:
    image: "bitnami/mariadb:latest"
    labels:
      kompose.service.type: nodeport
    ports:
      - "3306:3306"
    volumes:
      - "./mariadb_data:/bitnami"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: "bitnami/redis:latest"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6379:6379"
    volumes:
      - "./redis_data:/bitnami/redis"
  postgresql:
    image: "bitnami/postgresql:latest"
    labels:
      kompose.service.type: nodeport
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql_data:/bitnami"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mongodb_data:
    driver: local
  mariadb_data:
    driver: local
  redis_data:
    driver: local
  postgresql_data:
    driver: local
